use VIRTUALHA;

INSERT INTO ALOCACOES VALUES
	(NULL, 'PMVT', 'PREFEITURA MUNICIPAL DE VIRTUALHA', 'ADMINISTRACÃO EXECUTIVA DO MUNICÍPIO DE VIRTUALHA'),
	(NULL, 'CEEV', 'CIA DE ENERGIA ELÉTRICA DE VIRTUALHA', 'GERAÇÃO E DISTRIBUIÇÃO DE ENERGIA ELÉTRICA'),
    (NULL, 'CAEV', 'CIA DE ÁGUAS E ESGOTOS DE VIRTUALHA', 'RESPONSÁVEL PELA CAPTAÇÃO, DISTRIBUIÇÃO E PROCESSAMENTO DE ÁGUA POTÁVEL OU DE DESCARTE'),
    (NULL, 'CCPL', 'CIA DE COLETA E PROCESSAMENTO DE LIXO', 'RESPONSÁVEL PELA COLETA, RECICLAGEM E INCINERAÇÃO DE LIXO E GERAÇÃO DE ENERGIA RENOVÁVEL'),
    (NULL, 'SIEF', 'SECRETARIA DA INDÚSTRIA DE EXPLORAÇÃO FLORESTAL', 'RESPONSÁVEL PELAS ATIVIDADES DE EXTRATIVISMO E BENEFICIAMENTO FLORESTAL'),
    (NULL, 'SIAP', 'SECRETARIA DA INDÚSTRIA DE AGRICULTURA E PECUÁRIA', 'RESPONSÁVEL PELAS ATIVIDADES DE AGRICULTURA, PECUÁRIA E BENEFICIAMENTO DE BENS E PRODUTOS DE ORIGEM VEGETAL E ANIMAL'),
    (NULL, 'SIEM', 'SECRETARIA DA INDÚSTRIA DE EXPLORAÇÃO MINERAL', 'RESPONSÁVEL PELAS ATIVIDADES DE MINERAÇÃO E E DERIVADOS'),
    (NULL, 'SIEP', 'SECRETARIA DA INDÚSTRIA DE EXPLORAÇÃO PETROLÍFERA', 'RESPONSÁVEL PELAS ATIVIDADES DE EXTRAÇÃO, REFINAMENTO DE PETRÓLEO E PRODUTOS DERIVADOS'),
    (NULL, 'SAAG', 'SECRETARIA DE ADMINISTRAÇÃO DE ARMAZÉNS GERAIS', 'RESPONSÁVEL PELA REDE DE ARMAZÉNS LOGÍSTICOS GERAIS'),
    (NULL, 'SIEV', 'SECRETARIA DA INDÚSTRIA ESPECIALIZADA DE VIRTUALHA', 'RESPONSÁVEL PELA REDE DE FÁBRICAS DE PRODUTOS ESPECÍFICOS'),
    (NULL, 'SIPA', 'SECRETARIA DA INDÚSTRIA DE PESCA E AQUICULTURA', 'RESPONSÁVEL PELA REDE DE PORTOS DE PESCA, FAZENDAS DE AQUICULTURA, FÁBRICAS DE PRODUTOS DERIVADOS DA PESCA E MERCADOS DE PEIXE'),
    (NULL, 'SUSV', 'SERVIÇO ÚNICO DE SAÚDE DE VIRTUALHA', 'RESPONSÁVEL PELOS SERVIÇOS DE SAÚDE EM GERAL E ESTRUTURAS SANITÁRIAS POST MORTEM'),
    (NULL, 'CMBV', 'CORPO DE BOMBEIROS MILITARES DE VIRTUALHA', 'RESPONSÁVEL PELOS DESTACAMENTOS MILITARES DE BOMBEIROS E PELAS ESTRUTURAS DE PREVENÇÃO DE INCÊNCDIOS E DESASTRES'),
    (NULL, 'DPMV', 'DEPARTAMENTO DE POLÍCIA MILITAR DE VIRTUALHA', 'RESPONSÁVEL PELAS FORÇAS POLICIAIS E CASAS DE DETENÇÃO'),
    (NULL, 'SECV', 'SECRETARIA DA EDUCAÇÃO E CULTURA DE VIRTUALHA', 'RESPONSÁVEL PELO SISTEMA E ESTRUTURAS DE EDUCAÇÃO, CULTURA E CIDADÂNIA'),
    (NULL, 'STGV', 'SECRETARIA DE TRANSPORTES GERAIS DE VIRTUALHA', 'RESPONSÁVEL PELA ESTRUTURA DE TRANSPORTES PÚBLICOS GERAIS'),
    (NULL, 'SSPV', 'SECRETARIA DE SERVIÇOS POSTAIS DE VIRTUALHA', 'RESPONSÁVEL PELA ESTRUTURA DE SERVIÇOS POSTAIS DO MUNICÍPIO'),
    (NULL, 'DERP', 'DEPARTAMENTO DE ESTRADAS DE RODAGEM E PEDÁGIOS', 'RESPONSÁVEL PELA MALHA VIÁRIA E PRAÇAS DE PEDÁGIO'),
    (NULL, 'DAPP', 'DEPARTAMENTO DE ADMINISTRAÇÃO DE PRAÇAS E PARQUES', 'RESPONSÁVEL POR PRAÇAS, PARQUES E ESTRUTURAS ESPECIAIS DE INTEGRAÇÃO SOCIAL E EDIFÍCIOS DE MANUTENÇÃO'),
    (NULL, 'JAEE', 'JUNTA ADMINISTRATIVA DOS EDIFÍCIOS ESPECIAIS', 'RESPONSÁVEL PELAS ESTRUTURAS E ADMINISTRAÇÃO DE PRÉDIOS ESPECIAIS DE NATUREZA DIVERSA');

UPDATE ALOCACOES SET DESCRI = 'RESPONSÁVEL PELA CAPTAÇÃO, DISTRIBUIÇÃO E PROCESSAMENTO DE ÁGUA POTÁVEL OU DE DESCARTE' WHERE ID_ALOC = 3;